version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/ntc-edge-internal

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Android Build
          command: npx eas-cli build --platform android --non-interactive
          no_output_timeout: 1h
      - run:
          name: IOS Build
          command: npx eas-cli build --platform ios --non-interactive
          no_output_timeout: 1h

workflows:
  build_app:
    jobs:
      - build-approval:
          type: approval
          filters:
            branches:
              only:
                - master
                - develop
      - build:
          requires:
            - build-approval
          
          