version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/ntc-edge-internal

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Android Build
          command: npx eas-cli build --platform android --non-interactive
          no_output_timeout: 30m
      - run:
          name: IOS Build
          command: npx eas-cli build --platform ios --non-interactive
          no_output_timeout: 30m
  submit:
    executor: default
    steps:
      - checkout
      - run:
          name: Submit to Apple Appstore
          command: npx eas-cli submit -p ios --latest --non-interactive

workflows:
  build_app:
    jobs:
      - build:
          type: approval
          filters:
            branches:
              only:
                - master
                - develop
      - submit:
          type: approval
          requires:
            - build

          
          