version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/ntc-edge-internal

jobs:
  stage:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Android Build
          command: npx eas-cli build --platform android --non-interactive
      - run:
          name: IOS Build
          command: npx eas-cli build --platform ios --non-interactive

workflows:
  build_app:
    jobs:
      - stage:
          filters:
            branches:
              only:
                - master
                - develop
      - hold:
          type: approval
          requires:
            - stage
      - build:
          requires:
            - hold
          