version: 2.1

parameters:
  test-url:
    type: string
    default: "https://test-edge-application-processing-appsvc.azurewebsites.net"
  prod-url:
    type: string
    default: "https://prod-edge-application-processing-appsvc.azurewebsites.net"

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/ntc-edge-internal

jobs:
  App Build for Testing:
    executor: default
    environment:
      API_URL: << pipeline.parameters.test-url >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Android Build
          command: npx eas-cli build --platform android --non-interactive
          no_output_timeout: 30m
      - run:
          name: IOS Build
          command: npx eas-cli build --platform ios --non-interactive
          no_output_timeout: 30m
  App Build for Production:
    executor: default
    environment:
      API_URL: << pipeline.parameters.prod-url >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Android Build
          command: npx eas-cli build --platform android --non-interactive
          no_output_timeout: 30m
      - run:
          name: IOS Build
          command: npx eas-cli build --platform ios --non-interactive
          no_output_timeout: 30m
  Submit to Appstore:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Submit to Apple Appstore
          command: npx eas-cli submit -p ios --latest --non-interactive

workflows:
  Build and Deploy:
    jobs:
      - Build for Testing:
          type: approval
          filters:
            branches:
              only:
                - master
                - develop
      - Build for Production:
          type: approval
          filters:
            branches:
              only:
                - master
                - develop
      - App Build for Testing:
          context: ntc-edge
          requires:
            - Build for Testing
      - App Build for Production:
          context: ntc-edge
          requires:
            - Build for Production
      - Request for Submit Testing Build:
          type: approval
          requires:
            - App Build for Testing
      - Request for Submit Production Build:
          type: approval
          requires:
            - App Build for Production
      - Submit to Appstore:
          context: ntc-edge
          requires:
            - Request for Submit Testing Build
      - Submit to Appstore:
          context: ntc-edge
          requires:
            - Request for Submit Production Build         
          