version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/ntc-edge-internal

  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Android Build
          command: npx eas-cli build --platform android --non-interactive
      - run:
          name: IOS Build
          command: npx eas-cli build --platform ios --non-interactive

workflows:
  build_app:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
                - develop
          
          