version: 2.1

parameters:
  test_url:
    type: string
    default: "https://test-edge-application-processing-appsvc.azurewebsites.net"
  prod_url:
    type: string
    default: "https://prod-edge-application-processing-appsvc.azurewebsites.net"

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/ntc-edge-internal

jobs:
  Build App:
    executor: default
    parameters:
      api_url:
        type: string
    environment:
      API_URL: << parameters.api_url >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Android Build
          command: |
            echo building for ${API_URL}
            npx eas-cli build --platform android --non-interactive
          no_output_timeout: 30m
      - run:
          name: IOS Build
          command: |
            echo building for ${API_URL}
            npx eas-cli build --platform ios --non-interactive
          no_output_timeout: 30m
  Submit to Appstore:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Submit to Apple Appstore
          command: npx eas-cli submit -p ios --latest --non-interactive

workflows:
  Development Build and Deploy:
    jobs:
      - Build for Testing:
          type: approval
          filters:
            branches:
              only:
                - develop
      - Build App:
          api_url: << pipeline.parameters.test_url >>
          context: ntc-edge
          requires:
            - Build for Testing
      - Ready for Submission:
          type: approval
          requires:
            - Build App
      - Submit to Appstore:
          context: ntc-edge
          requires:
            - Ready for Submission
  Production Build and Deploy:
    jobs:
      - Build for Production:
          type: approval
          filters:
            branches:
              only:
                - master
      - Build App:
          api_url: << pipeline.parameters.prod_url >>
          context: ntc-edge
          requires:
            - Build for Production
      - Ready for Submission:
          type: approval
          requires:
            - Build App
      - Submit to Appstore:
          context: ntc-edge
          requires:
            - Ready for Submission    
          