import keyMirror from 'key-mirror';

export default keyMirror({
  SET_MEETINGS: null,
  ADD_TO_MEETINGS: null,
  ADD_MEETING: null,
  UPDATE_MEETING: null,
  REMOVE_MEETING: null,
  SET_MEETING: null,
  SET_MEETING_ID: null,
  SET_MEETING_PARTICIPANTS: null,
  ADD_MEETING_PARTICIPANTS: null,
  UPDATE_MEETING_PARTICIPANTS: null,
  REMOVE_MEETING_PARTICIPANTS: null,
  ADD_ACTIVE_MEETING: null,
  UPDATE_ACTIVE_MEETING: null,
  REMOVE_ACTIVE_MEETING: null,
  RESET_MEETING: null,
  CONNECTION_STATUS: null,
});
