export default function useApplicant(props) {
    const applicant = props?.applicant ,
        selectedTypes = props?.selectedTypes ,
        applicationType = props?.applicationType ,
        service = props?.service ,
        soa = props?.soa ,
        totalFee = props?.totalFee ,
        paymentMethod = props?.paymentMethod ,
        paymentHistory = props?.paymentHistory ,
        requirements = props?.requirements || props?.service?.applicationType?.requirements ,
        updatedAt = props?.updatedAt ,
        approvalHistory = props?.approvalHistory ,
        assignedPersonnel = props?.assignedPersonnel,
        schedule = props?.schedule,
        createdAt = props?.createdAt ,
        proofOfPayment = props?.proofOfPayment,
        documents = props?.document,
        tempdocuments = props?.tempdocument,
        remarks=  props?.remarks,
        paymentStatus = props?.paymentStatus,
        saved = props.saved
    return {applicant,
        selectedTypes,
        saved,
        applicationType,
        service,
        soa,
        totalFee,
        paymentMethod,
        requirements,
        updatedAt,
        approvalHistory ,
        assignedPersonnel,
        createdAt,
        schedule,
        documents,
        tempdocuments,
        remarks,
        paymentStatus,
        paymentHistory,
        proofOfPayment}
}
