import keyMirror from 'key-mirror';

export default keyMirror({
  SET_PINNED_APPLICATION: null,
  SET_NOT_PINNED_APPLICATION: null,
  UPDATE_APPLICATION_STATUS: null,
  SET_APPLICATIONS: null,
  DELETE_APPLICATIONS: null,
  HANDLE_LOAD: null,
  READ_UNREAD_APPLICATIONS: null,
  SET_TAB_BAR_HEIGHT: null,
  SET_APPLICATION_ITEM: null,
  SET_FILTER_RECT: null,
  SET_RIGHT_LAYOUT_COMPONENT: null,
  SET_TOPBARNAV: null,
  SET_ACTIVITY_SIZE: null,
  SET_SELECTED_YPOS: null,
  UPDATE_APPLICATIONS: null,
  SET_HAS_CHANGE: null,
  SET_EDIT: null,
  SET_USER_PROFILE_FORM: null,
  SET_USER_ORIGINAL_PROFILE_FORM: null,
  UPDATE_CHANGE_EVENT: null,
  SET_DATA: null
});
