name: EAS Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 5.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS ANDROID
        run: npx eas-cli build --profile development --platform android --non-interactive
      
      - name: Build on EAS IOS
        run: npx eas-cli build --platform ios --non-interactive
